
sdv:
  stackName: sdv-aqml-api-cumulus
  stackNameNoDash: SdvAqmlApiCumulus

  apiStage: dev

  vpc:
    vpcId: vpc-f3eabb8a
    subnets:
      - subnet-a3902fda

  ecs:
    instanceType: t2.micro
    desiredInstances: 0
    availabilityZone: us-west-2a

  buckets:
    internal: sdv-aqml-api-internal
    private: sdv-aqml-api-private
    protected: sdv-aqml-api-protected
    public: sdv-aqml-api-public

  iams:
    ecsRoleArn: arn:aws:iam::634640097461:role/sdv-aqml-api-cumulus-ecs
    lambdaApiGatewayRoleArn: arn:aws:iam::634640097461:role/sdv-aqml-api-cumulus-lambda-api-gateway
    lambdaProcessingRoleArn: arn:aws:iam::634640097461:role/sdv-aqml-api-cumulus-lambda-processing
    stepRoleArn: arn:aws:iam::634640097461:role/sdv-aqml-api-cumulus-steprole
    instanceProfile: arn:aws:iam::634640097461:instance-profile/sdv-aqml-api-cumulus-ecs

    urs_url: https://uat.urs.earthdata.nasa.gov/ #make sure to include the trailing slash

    # if not specified the value of the apigateway backend endpoint is used
    # api_backend_url: https://apigateway-url-to-api-backend/ #make sure to include the trailing slash

    # if not specified the value of the apigateway dist url is used
    # api_distribution_url: https://apigateway-url-to-distribution-app/ #make sure to include the trailing slash

  # URS users who should have access to the dashboard application.
  # users:
    # - username: <user1>
