default:
  prefix: sdv-aqml-api-cumulus
  stackName: sdv-aqml-api-cumulus-iam
  authorizor: false
  capabilities:
    - CAPABILITY_NAMED_IAM
  buckets:
    internal: sdv-aqml-api-internal
    private: sdv-aqml-api-private
    protected: sdv-aqml-api-protected
    public: sdv-aqml-api-public

  params:
     - name: ResourcePrefix
       value: '{{prefix}}'
     - name: InternalBucketName
       value: '{{buckets.internal}}'
     - name: PrivateBucketName
       value: '{{buckets.private}}'
     - name: ProtectedBucketName
       value: '{{buckets.protected}}'
     - name: PublicBucketName
       value: '{{buckets.public}}'
